# Generated by Django 5.2.6 on 2025-11-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typingtest',
            old_name='date',
            new_name='created_at',
        ),
    ]
