# Generated by Django 5.2.6 on 2025-11-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingapp', '0002_rename_date_typingtest_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typingtest',
            old_name='created_at',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='typingtest',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
    ]
