# Generated by Django 5.2.6 on 2025-11-05 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingapp', '0003_rename_created_at_typingtest_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField()),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('source_text', models.TextField()),
                ('typed_text', models.TextField()),
                ('correct_chars', models.IntegerField()),
                ('total_typed_chars', models.IntegerField()),
                ('errors', models.IntegerField()),
                ('wpm', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TypingTest',
        ),
    ]
