# Generated by Django 5.2.6 on 2025-12-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingapp', '0004_testresult_delete_typingtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('meaning', models.TextField()),
                ('synonyms', models.TextField(help_text='Comma separated')),
                ('antonyms', models.TextField(help_text='Comma separated')),
                ('sentence1', models.TextField()),
                ('sentence2', models.TextField()),
                ('sentence3', models.TextField()),
            ],
        ),
    ]
