# Generated by Django 5.2.6 on 2025-12-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingapp', '0006_vocabularyquestion_vocabularytestresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='char_errors',
            field=models.JSONField(default=dict),
        ),
    ]
