# Generated by Django 5.2.6 on 2025-12-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingapp', '0007_testresult_char_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyquestion',
            name='question_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vocabularyquestion',
            name='question_type',
            field=models.CharField(choices=[('meaning', 'Meaning'), ('synonym', 'Synonym'), ('antonym', 'Antonym'), ('usage', 'Correct Usage')], default='meaning', max_length=20),
        ),
    ]
